---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-python-template
  description: Template para aplicação Python (Django, FastAPI ou Flask)
spec:
  type: template
  lifecycle: experimental
  owner: user:guest
